'use client'
import { useMemo, useState } from 'react'
import { SlidersHorizontal, X, Search } from 'lucide-react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import VehicleCard from '@/components/VehicleCard'
import Reveal from '@/components/Reveal'
import { vehicles } from '@/lib/data'
const brands=['All brands',...Array.from(new Set(vehicles.map(v=>v.brand)))]; const fuels=['All fuel','Petrol','Diesel']; const transmissions=['All transmission','Automatic','Manual']; const bodies=['All body','SUV','Sedan'];
export default function Cars(){const [brand,setBrand]=useState('All brands');const [fuel,setFuel]=useState('All fuel');const [transmission,setTransmission]=useState('All transmission');const [body,setBody]=useState('All body');const [query,setQuery]=useState('');const [sort,setSort]=useState('Newest added'); const [mobile,setMobile]=useState(false); const filtered=useMemo(()=>{let r=vehicles.filter(v=>(brand==='All brands'||v.brand===brand)&&(fuel==='All fuel'||v.fuel===fuel)&&(transmission==='All transmission'||v.transmission===transmission)&&(body==='All body'||v.body===body)&&(`${v.brand} ${v.model} ${v.variant}`.toLowerCase().includes(query.toLowerCase()))); if(sort==='Price low-to-high')r.sort((a,b)=>a.price-b.price);if(sort==='Price high-to-low')r.sort((a,b)=>b.price-a.price);if(sort==='Lowest kilometres')r.sort((a,b)=>a.kilometres-b.kilometres);if(sort==='Newest year')r.sort((a,b)=>b.year-a.year);return r},[brand,fuel,transmission,body,query,sort]); const reset=()=>{setBrand('All brands');setFuel('All fuel');setTransmission('All transmission');setBody('All body');setQuery('')}; const Filter=()=> <div className="space-y-7">{[['Brand',brands,brand,setBrand],['Fuel',fuels,fuel,setFuel],['Transmission',transmissions,transmission,setTransmission],['Body',bodies,body,setBody]].map(([label,opts,value,setter])=><div key={label as string}><p className="mb-3 text-xs uppercase tracking-[.15em] text-black/45">{label as string}</p><div className="flex flex-wrap gap-2">{(opts as string[]).map(o=><button key={o} onClick={()=> (setter as React.Dispatch<React.SetStateAction<string>>)(o)} className={`border px-3 py-2 text-xs ${(value as string)===o?'border-black bg-black text-white':'border-black/15'}`}>{o}</button>)}</div></div>)}</div>;
return <><Header/><main className="pt-24"><div className="mx-auto max-w-[1440px] px-5 py-12 md:px-8 md:py-20"><Reveal><div className="flex flex-col justify-between gap-8 border-b border-black/10 pb-10 lg:flex-row lg:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-black/45">Inventory / {vehicles.length} cars</p><h1 className="display mt-4 text-6xl leading-none md:text-8xl">Find the<br/>right one.</h1></div><p className="max-w-sm text-sm leading-7 text-black/55">Search a curated inventory by what matters: brand, fuel, transmission, body style and price.</p></div></Reveal><div className="mt-8 flex flex-col gap-8 lg:flex-row"><aside className="hidden w-[250px] shrink-0 lg:block"><Filter/></aside><div className="min-w-0 flex-1"><div className="flex flex-col gap-3 border-b border-black/10 pb-5 sm:flex-row"><div className="flex flex-1 items-center border border-black/15 bg-white/20 px-3"><Search className="h-4 w-4 text-black/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search make, model or variant" className="w-full bg-transparent px-3 py-3 text-sm outline-none"/></div><button onClick={()=>setMobile(true)} className="border border-black/15 px-4 py-3 text-sm lg:hidden"><SlidersHorizontal className="mr-2 inline h-4 w-4"/> Filters</button><select value={sort} onChange={e=>setSort(e.target.value)} className="border border-black/15 bg-transparent px-4 py-3 text-sm outline-none"><option>Newest added</option><option>Price low-to-high</option><option>Price high-to-low</option><option>Newest year</option><option>Lowest kilometres</option></select></div><div className="mt-6 flex items-center justify-between"><p className="text-sm text-black/50">{filtered.length} result{filtered.length!==1?'s':''}</p><button onClick={reset} className="text-xs underline underline-offset-4">Reset</button></div><div className="mt-6 grid gap-5 md:grid-cols-2">{filtered.map(v=><Reveal key={v.id}><VehicleCard v={v}/></Reveal>)}</div>{filtered.length===0&&<div className="border border-dashed border-black/20 p-16 text-center"><h2 className="display text-4xl">Nothing matches that brief.</h2><button onClick={reset} className="mt-5 border border-black px-5 py-3 text-sm">Clear filters</button></div>}</div></div></div></main>{mobile&&<div className="fixed inset-0 z-[60] bg-[#f7f5f0] p-5 lg:hidden"><div className="flex items-center justify-between"><h2 className="display text-3xl">Filters</h2><button onClick={()=>setMobile(false)}><X/></button></div><div className="mt-10"><Filter/></div><button onClick={()=>setMobile(false)} className="mt-10 w-full bg-black px-5 py-3 text-sm font-semibold text-white">Show {filtered.length} cars</button></div>}<Footer/></>}
